Dz0 added on branch dz
Serggiolysen/SergeiLysenkoAndroid2019 pull request #1
Opened 2019-06-16 20:39 UTC by Serggiolysen

2019-06-17 03:59 UTC, stopstress approved these changes

2019-06-17 03:59 UTC, stopstress commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Код рабочий, но для удобства поддержки стоило бы вынести 4 повторяющиеся строчки из каждого листенера в отдельную функцию. Мой вариант для примера: https://github.com/stopstress/RadyukAndroidPvt/blob/Dz1/app/src/main/java/by/stress/radyukandroidpvt/dz0/Dz0Activity.kt

2019-06-17 04:04 UTC, Serggiolysen commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Ага, спасибо. Просто еще не дошел в изучении котлин до этой темы)

2019-06-17 04:18 UTC, stopstress commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Не думаю, что я смогу объяснить, почему не получалось - надо будет у Тимофея спросить)

2019-06-17 13:05 UTC, Serggiolysen commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Нашел как и понял, что мало чего понял) буду читать/учить котлин

2019-06-17 19:54 UTC, stopstress commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Вот неплохой онлайн-курс: https://www.coursera.org/learn/vvedenie-v-yazyk-kotlin/home/welcome

2019-06-18 11:31 UTC, tim-teacher requested changes
Нужно поправить все замечания

2019-06-18 11:31 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            val tmpText = textView0.getText().toString()
а зачем еще и .toString() вызывать?

2019-06-18 11:31 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
Да, нужно в отдельный метод вынести и его вызывать

2019-06-18 20:17 UTC, Serggiolysen commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            textView0.setText(textView1.getText())
поправи

> Да, нужно в отдельный метод вынести и его вызывать

исправил 2 замечания. запушил

2019-06-18 20:17 UTC, Serggiolysen commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +            val tmpText = textView0.getText().toString()
исправил

2019-06-22 09:21 UTC, tim-teacher approved these changes
Апрув но поправь те замечание которое написал.

2019-06-22 09:21 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvtjune/dz/dz0/Dz0.kt
> +        fun exchange() {
вынесите метод отдельно, а не внутри onCreate()

2019-06-23 08:25 UTC, merged